### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by LiamOxley** [RobinStephenson/jbt#15]
Tile art (one for each player and a neutral), sprite for roboticon, ore and energy image

**Comment by RobinStephenson** [comment]
@LiamOxley is this done now? if so we can close the issue and create new ones for new art if necessary

**Comment by LiamOxley** [comment]
Oh yes, sorry I didn't close this before. As long as people have no problems with what's there.

**Comment by RobinStephenson** [comment]
Dont worry. If not we can always reopen
