### ISSUE TITLE
ItemType not found in namespace

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt#17]
I think when we moved ItemType into its own file but in the tests folder the actual inventory class cant find it. Can we move it in with the rest of the code and is there a way we can get the tests to reference it from there without having to have 2 copies of the same file?

**Comment by Mikeywalsh** [comment]
Sorry, was my bad. I've moved it in the new pull request. 2 copies aren't needed. Game code can't access test code but test code can access game code.
