### ISSUE TITLE
Market should throw an error if someone tries to buy something when it is closed

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt#20]
This is so that we can enforce the time limits on phases

**Comment by LiamOxley** [comment]
Fixed the error message.

**Comment by RobinStephenson** [comment]
@LiamOxley Usually its better to leave the issue open until youve made a pull request with your changes, and just right Fixes #issuenumhere in the pull request and it will auto close this when its mergerd. Cause otherwise it looks like master right now doesnt have this issue but the change isnt there yet
