### ISSUE TITLE
Create a RoboticonFactory

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt#22]
A method for producing for the market based on its inventory.
Method for players to buy roboticons for a fee
Method for players to customise roboticons for a fee.
Should throw an error if player interactions happen in the wrong phase

**Comment by RobinStephenson** [comment]
Clarification:
Players do not buy roboticons from here, they buy them from the market. But can do so only during the phase for buying roboticons and not during the trading phase.

**Comment by Mart500** [comment]
Roboticon Factory Merged into Market Class.
