### ISSUE TITLE
Create a get for roboticons in an inventory

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt#37]
Create a getter to allow people to see a list of roboticons in a players inventory

**Comment by Mikeywalsh** [comment]
I thought that we didn't store actual roboticon references in the inventory? They are just a number in the inventory and are only actually a 'Roboticon' when you put them on a tile. If you take one off a tile, it just adds one back to the inventory.

When we were negotiating requirements, it was brought up that as soon as you take a roboticon off a tile, it reverts back to the base roboticon, so it would make no sense to actually store them in the inventory, right?

**Comment by Mart500** [comment]
That's correct. But there's also the fact that not every tile the player owns would have a roboticon on it. To find the amount produced each turn every tile would have to be checked rather than just tiles with roboticons. It's more inefficient, but still works. Depends on preference.

**Comment by Mikeywalsh** [comment]
I can do if you want, but then what am i supposed to do with the way im currently storing them? Will i have to change the way I store roboticons completely? And it does kind of over complicate it a bit. I know what you mean by efficiency but assuming if the map is like 40*40, which it probably won't be, its still only going to take a PC a fraction of a second to do the computation.

**Comment by Mart500** [comment]
I mean it's preference. If you don't think it will make too much of an impact then skip any extra work we don't need to do.

**Comment by RobinStephenson** [comment]
> When we were negotiating requirements, it was brought up that as soon as you take a roboticon off a tile, it reverts back to the base roboticon, so it would make no sense to actually store them in the inventory, right?

Are you sure? if so this wont be neccessary. Still I think its worth considering as it makes our code more adaptable in the future.

**Comment by RobinStephenson** [comment]
The performance impact of storing a list of all the roboticons wont even be noticeable even on the worst computer. @Mikeywalsh is it a hard change to make?

**Comment by Mikeywalsh** [comment]
@RobinStephenson It shouldn't take too long, but will require a fair bit of testing. I can do it when Roboticon has been merged into the master branch. Theres just a few questions:

- Does this mean that roboticons are not stored in the (ItemType, Int) dictionary for inventories? Should Roboticons just be in their own list instead, even in the market?
- Just to be crystal clear, you want a list of owned tiles AND a list of owned roboticons?

**Comment by Mart500** [comment]
@Mikeywalsh If The performance impact is not large, it would be easier for
initisliastion of Roboticon as markets hold Roboticon inventory without
having them initialised. It would be easier to keep the ItemType as it is
also used in market.

**Comment by Mikeywalsh** [comment]
We can't do it like that unfortunately, both players and markets have to use the same way of storing them as they both use the inventory class

**Comment by Mart500** [comment]
@Mikeywalsh I understand, I just meant we should re-consider not having a roboticon list and just holding a tile list. It would be easier.

**Comment by RobinStephenson** [comment]
@Mikeywalsh Yeah a list of both. Up to you how you implement it (in the dictionary or separate from other items)

**Comment by RobinStephenson** [comment]
Is this issue resolved? if so does someone want to delete it

**Comment by Mart500** [comment]
Issue decided against implementing.
