### ISSUE TITLE
Finish Roboticon Testing

### ISSUE THREAD

**Issue by Mart500** [RobinStephenson/jbt#39]
Finish testing for roboticon, roboticon customisation and market classes.

**Comment by Mart500** [comment]
Updated all roboticon testing, will continue to do so when Tile is merged completely.

**Comment by Mart500** [comment]
Roboticon, Roboticon customisation and the updated market class have all had their testing updated.

**Comment by RobinStephenson** [comment]
@Mart500 reopening as the issue isnt solved until the pull request with the fix is merged. close this again by referencing the issue number when merging the pull request

**Comment by RobinStephenson** [comment]
#52
