### ISSUE TITLE
Create GetTilePrice and GetUnsoldTiles methods in Market

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt#44]

**Comment by RobinStephenson** [comment]
Is this implemented?

**Comment by tc975** [comment]
Apparently a list of unsold tiles is present in the estate agent, and tile already has a public getter for tile price which I forgot about. Because of this, this issue should probably be closed unless these things are still needed seperately in market which I assume they're not.

**Comment by RobinStephenson** [comment]
Oh yeah I can see price is done now but @Mikeywalsh is the unsold tiles method implemented in master or another branch?

**Comment by tc975** [comment]
Both methods present elsewhere in the code
