### ISSUE TITLE
Create a market method which returns the maximum quantity the market will buy of an item

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt#47]
implement Market.MaxWillBuy(ItemType) which should return the maximum quantity the shop will buy of an item. It should take into account how much money the market has, the market not wanting to own too much of an item (this doesnt have to be perfect, it could just be something like wont buy more than a constant in a round).
Return the min of the two above.

**Comment by RobinStephenson** [comment]
@Mart500 or @tc975 could one of you do this

**Comment by Mart500** [comment]
Added functionality into market class within the Tile-Player-Robo branch
