### ISSUE TITLE
Finishing up tile-player-robo

### ISSUE THREAD

**Issue by Mikeywalsh** [RobinStephenson/jbt#52]
Tidying and finishing classes in tile-player-robo, now that all 3 people have had their pull requests confirmed. Todo list includes:

1. Remove sprites folder, as it is unnessessary
2. Remove TilesGridTest scene
3. Add an ID field to AbstractPlayer, and make it work with the CreateTile test in TileTest
4. Finish ProduceTest in TileTest, and add any tests you deem appropriate
5. Fix roboticoncustomisation, it will not work with null as a parameter for prior customizations. Instead we should have a base customization that all new roboticons have that just have their multipliers set to x1, this is required for roboticons to function correctly anyway, since we go off their customization when calculating production returns for tiles. The base customization should be a static member of the roboticoncustomisation class.
6. Fix SuccessfulAddCustomisation in RoboticonTest and add any new tests if you can think of any.
7. Fix FinishUnstartedTest in TimeoutTest

**Comment by RobinStephenson** [comment]
Couldn't find the sprites folder when i cloned.
Couldnt find the TilesGridTestScene

**Comment by RobinStephenson** [comment]
Rather than an tile owner ID I think it makes more sense to have a reference to the player that owns it

**Comment by RobinStephenson** [comment]
I have however made a check that asserts a tile starts with null owner

**Comment by RobinStephenson** [comment]
Splitting this into smaller issues
