### ISSUE TITLE
Market.BuyRoboticonOre() should be private

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt#63]
I think only the market should decide whether it should perform this operation so it should be private not public. We dont want any class to be able to call this

**Comment by Mart500** [comment]
The issue with this is, how would the market know, that every turn it should run the function? As there is no update function or do phase function, there would be no way to control when it is called.

**Comment by RobinStephenson** [comment]
Does it need to know? It could just check how many roboticons it has left and buy some more if it needs some more everytime someone buys a roboticon or sells some ore to the market

**Comment by RobinStephenson** [comment]
@Mart500 is working on this i think

**Comment by Mart500** [comment]
I'd assumed that this function runs once per market phase? But I can implement it this way if you require @RobinStephenson

**Comment by RobinStephenson** [comment]
@Mart500 up to you, if you have it run once phase youll need to create a method for turn controller to call and let @Mikeywalsh know that it has to call it as hes working on the turn controller

**Comment by Mart500** [comment]
@Mikeywalsh How do you want this implemented?

**Comment by Mikeywalsh** [comment]
@RobinStephenson Are you sure this is how you want it implemented? I guess you could have another function in Market called NewTurn() or something, which updates once per full turn. At the moment I'm just having the market buy up to 5 ore per turn by calling BuyRoboticonOre directly. I think it's cleaner if we just allow the market to do this only once per turn

**Comment by Mikeywalsh** [comment]
Either way I wouldn't change this unless you can test it in unity and make sure you havent broken the game, I could do it now if you want

**Comment by Mart500** [comment]
I think a new turn function would be better @Mikeywalsh I'll implement this when I arrive at the meeting. It provides better flexibility.
