### ISSUE TITLE
Remove temp code from Inventory when ready

### ISSUE THREAD

**Issue by RobinStephenson** [RobinStephenson/jbt#68]

**Comment by RobinStephenson** [comment]
Wait for @Mikeywalsh to say his code doesnt need this anymore

**Comment by Mart500** [comment]
Fair enough, I did a full search of the project and there was no other mention of it, I assume it's being used in another branch somewhere.

**Comment by RobinStephenson** [comment]
Yeah im not sure I just asked michael, sorry for not making the issue clearer that we need to wait
